[project]
name = "mealplanner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0",
    "gunicorn>=23.0.0",
    "markdown>=3.10",
    "python-dotenv>=1.2.1",
    "whitenoise>=6.11.0",
]
